Create spec for v6
ReviversMC/the-mod-index pull request #5
Opened 2022-08-05 00:50 UTC by Cloudate9

Remove depends and incompatible for mods, as we don't have a way to reliably handle that information
Create manual overrides for fields that we don't want the maintainer touching

2022-08-05 00:56 UTC, TacoMonkey11 approved these changes

2022-08-05 00:56 UTC, TacoMonkey11 approved these changes

2022-08-05 00:57 UTC, TacoMonkey11 approved these changes

2022-08-05 15:39 UTC, NebelNidas requested changes
Mod relations should be kept (see the Discord discussion), bit otherwise it's looking fine 👍

2022-08-06 02:29 UTC, Cloudate9 commented
The main concern for mod relations is that we don't have a reliable way of getting information. Take [sodium extra](https://web.archive.org/web/20220723123922/https://modrinth.com/mod/sodium-extra/version/mc1.19-0.4.6) for example, which should probably require sodium, but doesn't. Or lots of other mods, which should probably require the FAPI, but officially don't in their downloads page

If we do retain mod relations, we would have no way of knowing the validity of these relations without parsing a file like mods.toml or fabric.mod.json. A middle ground could be to retain the vastly under-declared mod relations, but have mods.toml/fabric.mod.json/others parsing for mod relations planned for the [TMI Maintainer](https://github.com/reviversmc/the-mod-index-creator/creator), eta unknown

2022-08-06 18:43 UTC, Cloudate9 commented
As we are keeping relations, this spec update is no longer a breaking change, and should be v5.1.0 instead of v6

2022-08-06 18:43 UTC, closed without merging